apiVersion: v1
version: 0.1.0
appVersion: 7.9.0
description: Enterprise Wiki Collaboration Platform.
name: atlassian-confluence
keywords:
- atlassian
- confluence
home: https://www.atlassian.com/software/confluence
sources:
- https://github.com/coulibal/docker-atlassian-confluence-software
