# https://github.com/coulibal/docker-atlassian-confluence-software.git

image:
  repository: fcouliba/atlassian-confluence-7.9.0
  tag: latest
  pullPolicy: IfNotPresent

confluence:
  javaHeapSize: 1024m
  javaMemoryOptions: "-XX:MaxMetaspaceSize=512m -XX:MaxDirectMemorySize=10m"
  javaOptions: ""

synchrony:
  ## disable Synchrony by default
  javaHeapSize: 0m

service:
  type: ClusterIP
  port: 8090
