# https://github.com/coulibal/docker-atlassian-jira-software.git

image:
  repository: fcouliba/atlassian-jira-8.12.0
  tag: latest
  pullPolicy: IfNotPresent

jira:
  javaHeapSize: 1024m
  javaMemoryOptions: "-XX:MaxMetaspaceSize=512m -XX:MaxDirectMemorySize=10m"
  javaOptions: ""

service:
  type: ClusterIP
  port: 8080
